### PR TITLE
DO NOT MERGE Consumer with message selectors

### PR DESCRIPTION
**Pull request by palmalcheg**

### CODE REVIEW

**Comment by palmalcheg** [comment]
So , we are using  RMQ as a Service on CF. Our application also used CXF to wire service interaction, JMS  is the transport. While binding RMQ to application is OK, service interaction failed with error :

```
2017-06-27T14:54:19.67+0300 [App/0]      OUT Caused by: java.lang.UnsupportedOperationException
2017-06-27T14:54:19.67+0300 [App/0]      OUT    at com.rabbitmq.jms.client.RMQSession.createConsumer(RMQSession.java:717)
2017-06-27T14:54:19.67+0300 [App/0]      OUT    at org.apache.cxf.transport.jms.util.MessageListenerContainer.start(MessageListenerContaine
2017-06-27T14:54:19.67+0300 [App/0]      OUT    at org.apache.cxf.transport.jms.JMSConduit.setupReplyDestination(JMSConduit.java:183)
2017-06-27T14:54:19.67+0300 [App/0]      OUT    at org.apache.cxf.transport.jms.JMSConduit.sendAndReceiveMessage(JMSConduit.java:195)
2017-06-27T14:54:19.67+0300 [App/0]      OUT    at org.apache.cxf.transport.jms.JMSConduit.sendExchange(JMSConduit.java:145)
2017-06-27T14:54:19.67+0300 [App/0]      OUT    at org.apache.cxf.transport.jms.MessageStreamUtil$SendingOutputStream.doClose(MessageStream
2017-06-27T14:54:19.67+0300 [App/0]      OUT    at org.apache.cxf.io.CachedOutputStream.close(CachedOutputStream.java:213)
2017-06-27T14:54:19.67+0300 [App/0]      OUT    at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
2017-06-27T14:54:19.67+0300 [App/0]      OUT    at org.apache.cxf.transport.jms.JMSConduit.close(JMSConduit.java:101)
2017-06-27T14:54:19.67+0300 [App/0]      OUT    at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handl
2017-06-27T14:54:19.67+0300 [App/0]      OUT    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
2017-06-27T14:54:19.68+0300 [App/0]      OUT    at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:677
2017-06-27T14:54:19.68+0300 [App/0]      OUT    at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:235)
```

**Comment by palmalcheg** [comment]
CXF 3.1.11
RabbitMQ 3.6.*

**Comment by michaelklishin** [comment]
@palmalcheg this PR simply removes a "not implemented" exception. Are you sure that message selectors are actually supported? [They are not](http://www.rabbitmq.com/jms-client.html) according to the docs and knowing the way RabbitMQ, RabbitMQ Java client and the protocol used by those two works, I tend to believe it. Maybe @acogoluegnes can correct me.

Why is this an acceptable solution for everyone?

**Comment by palmalcheg** [comment]
Comments inline :   
 >>> this PR simply removes a "not implemented" exception.

this PR handles the situation when message selector is not nullOrEmpty via delegating to *createConsumerInternal* . Moreover , CI checks have passed which means that either this is feasible solution or there is a gap in test coverage. One more thing - I've tested this on environment and seems it works - maybe there'll be some sideeffects latter but for now it's OK.

>>> According to documentation

Documentation apts to be not up-to-date or there are "undocumented" capabilities. 

Even through the naming *createConsumer(...) -> createConsumerInternal(...)* sounds sensible

**Comment by michaelklishin** [comment]
@palmalcheg if a feature is not supported and even documented as such, why would it have tests? This client uses a [modified version of the JMS compliance test suite](https://github.com/rabbitmq/rabbitmq-jms-cts) for exactly the same reason.

I'm afraid we are not ready to merge a change just because it does not throw an exception in a few scenarios.

**Pull request closed without merging**
